import { monthlyAdmissions, dailyAttendance, revenueData, bookIssueTrend, seatOccupancy, membershipGrowth, popularBooks } from '../data/staticData';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, AreaChart, Area, LineChart, Line, PieChart, Pie, Cell } from 'recharts';
import { Card } from '../components/UI';
const C = ['#3B82F6','#10B981','#F59E0B','#EF4444','#8B5CF6','#06B6D4','#EC4899','#F97316'];
const tip = { background:'rgba(15,23,42,0.95)',border:'1px solid rgba(255,255,255,0.1)',borderRadius:'4px',padding:'8px 12px',color:'#fff',fontSize:'12px' };
export default function AnalyticsPage() { return (
  <div><div className="mb-3"><h1 className="font-bold text-[#0F172A]" style={{fontSize:'0.92rem'}}>📈 Analytics Dashboard</h1><p className="text-[#64748B]" style={{fontSize:'0.62rem'}}>Visual insights and trends</p></div><div className="grid grid-cols-1 lg:grid-cols-2 gap-3">{[
    ['Monthly Admissions',<BarChart data={monthlyAdmissions}><CartesianGrid strokeDasharray="3 3" stroke="#F1F5F9" vertical={false} /><XAxis dataKey="month" tick={{fontSize:10,fill:'#94A3B8'}} axisLine={false} tickLine={false} /><YAxis tick={{fontSize:10,fill:'#94A3B8'}} axisLine={false} tickLine={false} width={28} /><Tooltip contentStyle={tip} /><Bar dataKey="count" fill="#6366F1" radius={[4,4,0,0]} /></BarChart>],
    ['Daily Attendance',<BarChart data={dailyAttendance}><CartesianGrid strokeDasharray="3 3" stroke="#F1F5F9" vertical={false} /><XAxis dataKey="day" tick={{fontSize:10,fill:'#94A3B8'}} axisLine={false} tickLine={false} /><YAxis tick={{fontSize:10,fill:'#94A3B8'}} axisLine={false} tickLine={false} width={28} /><Tooltip contentStyle={tip} /><Bar dataKey="present" fill="#10B981" radius={[4,4,0,0]} /></BarChart>],
    ['Revenue',<AreaChart data={revenueData}><CartesianGrid strokeDasharray="3 3" stroke="#F1F5F9" vertical={false} /><XAxis dataKey="month" tick={{fontSize:10,fill:'#94A3B8'}} axisLine={false} tickLine={false} /><YAxis tick={{fontSize:10,fill:'#94A3B8'}} axisLine={false} tickLine={false} tickFormatter={v=>`${v/1000}K`} width={32} /><Tooltip formatter={v=>`₹${Number(v).toLocaleString()}`} contentStyle={tip} /><Area type="monotone" dataKey="income" stroke="#10B981" fill="#10B981" fillOpacity={.1} /><Area type="monotone" dataKey="expense" stroke="#EF4444" fill="#EF4444" fillOpacity={.1} /></AreaChart>],
    ['Book Issues',<LineChart data={bookIssueTrend}><CartesianGrid strokeDasharray="3 3" stroke="#F1F5F9" vertical={false} /><XAxis dataKey="month" tick={{fontSize:10,fill:'#94A3B8'}} axisLine={false} tickLine={false} /><YAxis tick={{fontSize:10,fill:'#94A3B8'}} axisLine={false} tickLine={false} width={28} /><Tooltip contentStyle={tip} /><Line type="monotone" dataKey="issued" stroke="#8B5CF6" strokeWidth={2.5} dot={{fill:'#8B5CF6',r:3,strokeWidth:2,stroke:'#fff'}} /></LineChart>],
    ['Seat Occupancy',<AreaChart data={seatOccupancy}><CartesianGrid strokeDasharray="3 3" stroke="#F1F5F9" vertical={false} /><XAxis dataKey="time" tick={{fontSize:10,fill:'#94A3B8'}} axisLine={false} tickLine={false} interval="preserveStartEnd" /><YAxis tick={{fontSize:10,fill:'#94A3B8'}} axisLine={false} tickLine={false} width={28} /><Tooltip contentStyle={tip} /><Area type="monotone" dataKey="occupied" stroke="#F59E0B" fill="#F59E0B" fillOpacity={.12} /></AreaChart>],
    ['Membership Growth',<LineChart data={membershipGrowth}><CartesianGrid strokeDasharray="3 3" stroke="#F1F5F9" vertical={false} /><XAxis dataKey="month" tick={{fontSize:10,fill:'#94A3B8'}} axisLine={false} tickLine={false} /><YAxis tick={{fontSize:10,fill:'#94A3B8'}} axisLine={false} tickLine={false} width={28} /><Tooltip contentStyle={tip} /><Line type="monotone" dataKey="members" stroke="#06B6D4" strokeWidth={2.5} dot={{fill:'#06B6D4',r:3,strokeWidth:2,stroke:'#fff'}} /></LineChart>],
  ].map(([t,ch])=><Card key={t} className="p-4"><h3 className="font-bold text-[#0F172A] mb-1" style={{fontSize:'0.82rem'}}>{t}</h3><p className="text-[#64748B] mb-3" style={{fontSize:'0.6rem'}}>Trend analysis</p><ResponsiveContainer width="100%" height={200}>{ch}</ResponsiveContainer></Card>)}
    <Card className="p-4 lg:col-span-2"><h3 className="font-bold text-[#0F172A] mb-3" style={{fontSize:'0.82rem'}}>📖 Popular Books</h3><div className="grid grid-cols-1 lg:grid-cols-2 gap-3"><ResponsiveContainer width="100%" height={240}><BarChart data={popularBooks} layout="vertical" margin={{left:10}}><CartesianGrid strokeDasharray="3 3" stroke="#F1F5F9" horizontal={false} /><XAxis type="number" tick={{fontSize:10,fill:'#94A3B8'}} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="name" tick={{fontSize:10,fill:'#475569',fontWeight:600}} width={100} axisLine={false} tickLine={false} /><Tooltip contentStyle={tip} /><Bar dataKey="issues" radius={[0,4,4,0]}>{popularBooks.map((_,i)=><Cell key={i} fill={C[i%C.length]} />)}</Bar></BarChart></ResponsiveContainer><ResponsiveContainer width="100%" height={240}><PieChart><Pie data={popularBooks} dataKey="issues" nameKey="name" cx="50%" cy="50%" outerRadius={85} label={({name,percent})=>`${name} (${((percent||0)*100).toFixed(0)}%)`} labelLine={false} fontSize={9}>{popularBooks.map((_,i)=><Cell key={i} fill={C[i%C.length]} />)}</Pie><Tooltip contentStyle={tip} /></PieChart></ResponsiveContainer></div></Card>
  </div></div>
);}
