import { useState } from 'react';
import { bookIssues } from '../data/staticData';
import { Search, RotateCcw, BookOpen } from 'lucide-react';
import { Table, Td, StatusBadge, SummaryCard, Card, ToolbarBtn } from '../components/UI';

export default function BookIssuePage({ view='issue' }) {
  const [q, setQ] = useState(''); const [sf, setSf] = useState('All');
  const list = bookIssues.filter(b=>(b.student.toLowerCase().includes(q.toLowerCase())||b.book.toLowerCase().includes(q.toLowerCase()))&&(sf==='All'||b.status===sf));

  if(view==='return') return (
    <div><div className="mb-3"><h1 className="font-bold text-[#0F172A]" style={{fontSize:'0.92rem'}}>🔄 Book Return</h1></div><Card className="p-4 mb-3"><h3 className="font-bold text-[#0F172A] mb-3" style={{fontSize:'0.78rem'}}>Return Process</h3><div className="grid grid-cols-5 gap-2">{[{s:1,l:'Scan Book',i:'📖'},{s:2,l:'Scan Card',i:'🪪'},{s:3,l:'Calc Fine',i:'💰'},{s:4,l:'Update Stock',i:'📦'},{s:5,l:'Print Receipt',i:'🧾'}].map(x=><div key={x.s} className="text-center p-3 relative" style={{border:'1px solid #E2E8F0'}}><span className="absolute -top-2 -left-2 w-5 h-5 flex items-center justify-center text-white font-bold" style={{fontSize:'0.55rem',background:'#0F172A'}}>{x.s}</span><span className="text-lg">{x.i}</span><p className="text-[#0F172A] font-semibold mt-1" style={{fontSize:'0.68rem'}}>{x.l}</p></div>)}</div></Card><Card className="p-4 mb-3"><h3 className="font-bold text-[#0F172A] mb-3" style={{fontSize:'0.78rem'}}>Quick Return</h3><div className="grid grid-cols-2 gap-3"><div><label className="text-[#94A3B8] font-semibold uppercase block mb-1" style={{fontSize:'0.55rem',letterSpacing:'0.4px'}}>Book ID</label><input placeholder="Scan or enter" className="w-full outline-none text-[#0F172A]" style={{height:34,border:'1px solid #E2E8F0',padding:'0 10px',fontSize:'0.78rem'}} /></div><div><label className="text-[#94A3B8] font-semibold uppercase block mb-1" style={{fontSize:'0.55rem',letterSpacing:'0.4px'}}>Student ID</label><input placeholder="Scan or enter" className="w-full outline-none text-[#0F172A]" style={{height:34,border:'1px solid #E2E8F0',padding:'0 10px',fontSize:'0.78rem'}} /></div></div><div className="mt-3"><ToolbarBtn variant="primary"><RotateCcw size={13} /> Process Return</ToolbarBtn></div></Card><Table headers={['Student','Book','Return Date','Fine']}>{bookIssues.filter(b=>b.status==='Returned').map(b=><tr key={b.id} className="hover:bg-[#FAFBFF]"><Td className="font-bold">{b.student}</Td><Td>{b.book}</Td><Td>{b.returnDate}</Td><Td>{b.fine>0?<span className="font-extrabold text-[#DC2626]">₹{b.fine}</span>:<span className="text-[#94A3B8]">Nil</span>}</Td></tr>)}</Table></div>
  );

  return (
    <div><div className="mb-3"><h1 className="font-bold text-[#0F172A]" style={{fontSize:'0.92rem'}}>📚 Book Issue Module</h1></div><div className="grid grid-cols-5 gap-2 mb-3">{[{s:'Issued',b:'#EFF6FF'},{s:'Returned',b:'#ECFDF5'},{s:'Overdue',b:'#FEF2F2'},{s:'Lost',b:'#F9FAFB'},{s:'Damaged',b:'#FFF7ED'}].map(x=><SummaryCard key={x.s} label={x.s} value={bookIssues.filter(b=>b.status===x.s).length} icon={<BookOpen size={16} />} bgColor={x.b} />)}</div><Card className="p-2.5 mb-3 flex flex-wrap items-center gap-2"><div className="flex items-center gap-1.5 px-2.5 flex-1 min-w-[160px]" style={{height:34,border:'1px solid #E2E8F0'}}><Search className="w-3.5 h-3.5 text-[#94A3B8]" /><input className="bg-transparent outline-none w-full text-[#0F172A] placeholder:text-[#CBD5E1]" style={{fontSize:'0.78rem'}} placeholder="Search..." value={q} onChange={e=>setQ(e.target.value)} /></div>{['All','Issued','Returned','Overdue','Lost'].map(s=><ToolbarBtn key={s} variant={sf===s?'primary':'default'} onClick={()=>setSf(s)}>{s}</ToolbarBtn>)}</Card><Table headers={['#','Student','Book','Issue Date','Return Date','Fine','Status']}>{list.map((b,i)=><tr key={b.id} className="hover:bg-[#FAFBFF]"><Td className="text-[#94A3B8] font-bold text-center" align="center">{i+1}</Td><Td className="font-bold">{b.student}</Td><Td>{b.book}</Td><Td>{b.issueDate}</Td><Td>{b.returnDate}</Td><Td>{b.fine>0?<span className="font-extrabold text-[#DC2626]">₹{b.fine}</span>:<span className="text-[#94A3B8]">—</span>}</Td><Td align="center"><StatusBadge status={b.status} /></Td></tr>)}</Table></div>
  );
}
